const assert = require('assert');
const conjugateVerb = require('../createdb/conjugate');
const data2 = require('../createdb/JMdict.json');

describe('Conjugation tests', function(){
  it('Conjugate Ichidan Verb', function(done){
    var verbtest = data2[168233]['k_ele'][0]['keb'][0];
    var typetest = data2[168233]['sense'][0]['pos'][0];
    var ichidan = conjugateVerb.conjugate(verbtest, typetest);

    var ichidan_test = [ { form: 'Present',
    plainp: '薫じる',
    plainn: '薫じない',
    politep: '薫じます',
    politen: '薫じません' },
  { form: 'Past',
    plainp: '薫じた',
    plainn: '薫じなかった',
    politep: '薫じました',
    politen: '薫じませんでした' },
  { form: 'Te',
    plainp: '薫じて',
    plainn: '薫じなくて',
    politep: '薫じまして',
    politen: '薫じませんで' },
  { form: 'Present Progressive',
    plainp: '薫じている',
    plainn: '薫じていない',
    politep: '薫じています',
    politen: '薫じていません' },
  { form: 'Volitional',
    plainp: '薫じよう',
    plainn: '薫じまい',
    politep: '薫じましょう',
    politen: '薫じますまい' },
  { form: 'Desire (Present)',
    plainp: '薫じたい',
    plainn: '薫じたくない',
    politep: '薫じたいです',
    politen: '薫じたくないです' },
  { form: 'Desire (Past)',
    plainp: '薫じたかった',
    plainn: '薫じたくなかった',
    politep: '薫じたかったです',
    politen: '薫じたくなかったです' },
  { form: 'Conditional',
    plainp: '薫じたら',
    plainn: '薫じなかったら',
    politep: '薫じましたら',
    politen: '薫じませんでしたら' },
  { form: 'Provisional',
    plainp: '薫じれば',
    plainn: '薫じなければ',
    politep: '薫じますなら(ば)',
    politen: '薫じませんなら(ば)' },
  { form: 'Potential',
    plainp: '薫じられる',
    plainn: '薫じられない',
    politep: '薫じられます',
    politen: '薫じられません' },
  { form: 'Passive',
    plainp: '薫じられる',
    plainn: '薫じられない',
    politep: '薫じられます',
    politen: '薫じられません' },
  { form: 'Causative',
    plainp: '薫じさせる',
    plainn: '薫じさせない',
    politep: '薫じさせます',
    politen: '薫じさせません' },
  { form: 'Causative (Alt.)',
    plainp: '薫じさす',
    plainn: '薫じささない',
    politep: '薫じさします',
    politen: '薫じさしません' },
  { form: 'Causative Passive',
    plainp: '薫じさせられる',
    plainn: '薫じさせられない',
    politep: '薫じさせられます',
    politen: '薫じさせられません' },
  { form: 'Conjectural',
    plainp: '薫じるだろう',
    plainn: '薫じないだろう',
    politep: '薫じるでしょう',
    politen: '薫じないでしょう' },
  { form: 'Alternative',
    plainp: '薫じたり',
    plainn: '薫じなかったり',
    politep: '薫じましたり',
    politen: '薫じませんでしたり' },
  { form: 'Imperative',
    plainp: '薫じろ',
    plainn: '薫じるな',
    politep: '薫じなさい',
    politen: '薫じなさるな' } ];

    for (var i = 0; i < ichidan.length; i ++) {
      assert.deepStrictEqual(ichidan[i], ichidan_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "bu" ending', function(done){
    var verbtest = data2[51531]['k_ele'][0]['keb'][0];
    var typetest = data2[51531]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanbu_test = [ { 
    form: 'Present',
    plainp: '遊ぶ',
    plainn: '遊ばない',
    politep: '遊びます',
    politen: '遊びません' },
  { form: 'Past',
    plainp: '遊んだ',
    plainn: '遊ばなかった',
    politep: '遊びました',
    politen: '遊びませんでした' },
  { form: 'Te',
    plainp: '遊んで',
    plainn: '遊ばなくて',
    politep: '遊びまして',
    politen: '遊びませんで' },
  { form: 'Present Progressive',
    plainp: '遊んでいる',
    plainn: '遊んでいない',
    politep: '遊んでいます',
    politen: '遊んでいません' },
  { form: 'Volitional',
    plainp: '遊ぼう',
    plainn: '遊ぶまい',
    politep: '遊びましょう',
    politen: '遊びますまい' },
  { form: 'Desire (Present)',
    plainp: '遊びたい',
    plainn: '遊びたくない',
    politep: '遊びたいです',
    politen: '遊びたくないです' },
  { form: 'Desire (Past)',
    plainp: '遊びたかった',
    plainn: '遊びたくなかった',
    politep: '遊びたかったです',
    politen: '遊びたくなかったです' },
  { form: 'Conditional',
    plainp: '遊んだら',
    plainn: '遊ばなかったら',
    politep: '遊びましたら',
    politen: '遊びませんでしたら' },
  { form: 'Provisional',
    plainp: '遊べば',
    plainn: '遊ばなければ',
    politep: '遊びますなら(ば)',
    politen: '遊びませんなら(ば)' },
  { form: 'Potential',
    plainp: '遊べる',
    plainn: '遊べない',
    politep: '遊べます',
    politen: '遊べません' },
  { form: 'Passive',
    plainp: '遊ばれる',
    plainn: '遊ばれない',
    politep: '遊ばれます',
    politen: '遊ばれません' },
  { form: 'Causative',
    plainp: '遊ばせる',
    plainn: '遊ばせない',
    politep: '遊ばせます',
    politen: '遊ばせません' },
  { form: 'Causative (Alt.)',
    plainp: '遊ばす',
    plainn: '遊ばさない',
    politep: '遊ばします',
    politen: '遊ばしません' },
  { form: 'Causative Passive',
    plainp: '遊ばせられる',
    plainn: '遊ばせられない',
    politep: '遊ばせられます',
    politen: '遊ばせられません' },
  { form: 'Conjectural',
    plainp: '遊ぶだろう',
    plainn: '遊ばないだろう',
    politep: '遊ぶでしょう',
    politen: '遊ばないでしょう' },
  { form: 'Alternative',
    plainp: '遊んだり',
    plainn: '遊ばなかったり',
    politep: '遊びましたり',
    politen: '遊びませんでしたり' },
  { form: 'Imperative',
    plainp: '遊べ',
    plainn: '遊ぶな',
    politep: '遊びなさい',
    politen: '遊びなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanbu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "gu" ending', function(done){
    var verbtest = data2[15969]['k_ele'][0]['keb'][0];
    var typetest = data2[15969]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godangu_test = [ { form: 'Present',
    plainp: '泳ぐ',
    plainn: '泳がない',
    politep: '泳ぎます',
    politen: '泳ぎません' },
  { form: 'Past',
    plainp: '泳いだ',
    plainn: '泳がなかった',
    politep: '泳ぎました',
    politen: '泳ぎませんでした' },
  { form: 'Te',
    plainp: '泳いで',
    plainn: '泳がなくて',
    politep: '泳ぎまして',
    politen: '泳ぎませんで' },
  { form: 'Present Progressive',
    plainp: '泳いでいる',
    plainn: '泳いでいない',
    politep: '泳いでいます',
    politen: '泳いでいません' },
  { form: 'Volitional',
    plainp: '泳ごう',
    plainn: '泳ぐまい',
    politep: '泳ぎましょう',
    politen: '泳ぎますまい' },
  { form: 'Desire (Present)',
    plainp: '泳ぎたい',
    plainn: '泳ぎたくない',
    politep: '泳ぎたいです',
    politen: '泳ぎたくないです' },
  { form: 'Desire (Past)',
    plainp: '泳ぎたかった',
    plainn: '泳ぎたくなかった',
    politep: '泳ぎたかったです',
    politen: '泳ぎたくなかったです' },
  { form: 'Conditional',
    plainp: '泳いだら',
    plainn: '泳がなかったら',
    politep: '泳ぎましたら',
    politen: '泳ぎませんでしたら' },
  { form: 'Provisional',
    plainp: '泳げば',
    plainn: '泳がなければ',
    politep: '泳ぎますなら(ば)',
    politen: '泳ぎませんなら(ば)' },
  { form: 'Potential',
    plainp: '泳げる',
    plainn: '泳げない',
    politep: '泳げます',
    politen: '泳げません' },
  { form: 'Passive',
    plainp: '泳がれる',
    plainn: '泳がれない',
    politep: '泳がれます',
    politen: '泳がれません' },
  { form: 'Causative',
    plainp: '泳がせる',
    plainn: '泳がせない',
    politep: '泳がせます',
    politen: '泳がせません' },
  { form: 'Causative (Alt.)',
    plainp: '泳がす',
    plainn: '泳がさない',
    politep: '泳がします',
    politen: '泳がしません' },
  { form: 'Causative Passive',
    plainp: '泳がせられる',
    plainn: '泳がせられない',
    politep: '泳がせられます',
    politen: '泳がせられません' },
  { form: 'Conjectural',
    plainp: '泳ぐだろう',
    plainn: '泳がないだろう',
    politep: '泳ぐでしょう',
    politen: '泳がないでしょう' },
  { form: 'Alternative',
    plainp: '泳いだり',
    plainn: '泳がなかったり',
    politep: '泳ぎましたり',
    politen: '泳ぎませんでしたり' },
  { form: 'Imperative',
    plainp: '泳げ',
    plainn: '泳ぐな',
    politep: '泳ぎなさい',
    politen: '泳ぎなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godangu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "ku" ending', function(done){
    var verbtest = data2[93563]['k_ele'][0]['keb'][0];
    var typetest = data2[93563]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanku_test = [ { form: 'Present',
    plainp: '急く',
    plainn: '急かない',
    politep: '急きます',
    politen: '急きません' },
  { form: 'Past',
    plainp: '急いた',
    plainn: '急かなかった',
    politep: '急きました',
    politen: '急きませんでした' },
  { form: 'Te',
    plainp: '急いて',
    plainn: '急かなくて',
    politep: '急きまして',
    politen: '急きませんで' },
  { form: 'Present Progressive',
    plainp: '急いている',
    plainn: '急いていない',
    politep: '急いています',
    politen: '急いていません' },
  { form: 'Volitional',
    plainp: '急こう',
    plainn: '急くまい',
    politep: '急きましょう',
    politen: '急きますまい' },
  { form: 'Desire (Present)',
    plainp: '急きたい',
    plainn: '急きたくない',
    politep: '急きたいです',
    politen: '急きたくないです' },
  { form: 'Desire (Past)',
    plainp: '急きたかった',
    plainn: '急きたくなかった',
    politep: '急きたかったです',
    politen: '急きたくなかったです' },
  { form: 'Conditional',
    plainp: '急いたら',
    plainn: '急かなかったら',
    politep: '急きましたら',
    politen: '急きませんでしたら' },
  { form: 'Provisional',
    plainp: '急けば',
    plainn: '急かなければ',
    politep: '急きますなら(ば)',
    politen: '急きませんなら(ば)' },
  { form: 'Potential',
    plainp: '急ける',
    plainn: '急けない',
    politep: '急けます',
    politen: '急けません' },
  { form: 'Passive',
    plainp: '急かれる',
    plainn: '急かれない',
    politep: '急かれます',
    politen: '急かれません' },
  { form: 'Causative',
    plainp: '急かせる',
    plainn: '急かせない',
    politep: '急かせます',
    politen: '急かせません' },
  { form: 'Causative (Alt.)',
    plainp: '急かす',
    plainn: '急かさない',
    politep: '急かします',
    politen: '急かしません' },
  { form: 'Causative Passive',
    plainp: '急かせられる',
    plainn: '急かせられない',
    politep: '急かせられます',
    politen: '急かせられません' },
  { form: 'Conjectural',
    plainp: '急くだろう',
    plainn: '急かないだろう',
    politep: '急くでしょう',
    politen: '急かないでしょう' },
  { form: 'Alternative',
    plainp: '急いたり',
    plainn: '急かなかったり',
    politep: '急きましたり',
    politen: '急きませんでしたり' },
  { form: 'Imperative',
    plainp: '急け',
    plainn: '急くな',
    politep: '急きなさい',
    politen: '急きなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanku_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "ku" special (行く) ending', function(done){
    var verbtest = data2[56853]['k_ele'][0]['keb'][0];
    var typetest = data2[56853]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanku_test = [ { form: 'Present',
    plainp: '連れて行く',
    plainn: '連れて行かない',
    politep: '連れて行きます',
    politen: '連れて行きません' },
  { form: 'Past',
    plainp: '連れて行った',
    plainn: '連れて行かなかった',
    politep: '連れて行きました',
    politen: '連れて行きませんでした' },
  { form: 'Te',
    plainp: '連れて行って',
    plainn: '連れて行かなくて',
    politep: '連れて行きまして',
    politen: '連れて行きませんで' },
  { form: 'Present Progressive',
    plainp: '連れて行っている',
    plainn: '連れて行っていない',
    politep: '連れて行っています',
    politen: '連れて行っていません' },
  { form: 'Volitional',
    plainp: '連れて行こう',
    plainn: '連れて行くまい',
    politep: '連れて行きましょう',
    politen: '連れて行きますまい' },
  { form: 'Desire (Present)',
    plainp: '連れて行きたい',
    plainn: '連れて行きたくない',
    politep: '連れて行きたいです',
    politen: '連れて行きたくないです' },
  { form: 'Desire (Past)',
    plainp: '連れて行きたかった',
    plainn: '連れて行きたくなかった',
    politep: '連れて行きたかったです',
    politen: '連れて行きたくなかったです' },
  { form: 'Conditional',
    plainp: '連れて行ったら',
    plainn: '連れて行かなかったら',
    politep: '連れて行きましたら',
    politen: '連れて行きませんでしたら' },
  { form: 'Provisional',
    plainp: '連れて行けば',
    plainn: '連れて行かなければ',
    politep: '連れて行きますなら(ば)',
    politen: '連れて行きませんなら(ば)' },
  { form: 'Potential',
    plainp: '連れて行ける',
    plainn: '連れて行けない',
    politep: '連れて行けます',
    politen: '連れて行けません' },
  { form: 'Passive',
    plainp: '連れて行かれる',
    plainn: '連れて行かれない',
    politep: '連れて行かれます',
    politen: '連れて行かれません' },
  { form: 'Causative',
    plainp: '連れて行かせる',
    plainn: '連れて行かせない',
    politep: '連れて行かせます',
    politen: '連れて行かせません' },
  { form: 'Causative (Alt.)',
    plainp: '連れて行かす',
    plainn: '連れて行かさない',
    politep: '連れて行かします',
    politen: '連れて行かしません' },
  { form: 'Causative Passive',
    plainp: '連れて行かせられる',
    plainn: '連れて行かせられない',
    politep: '連れて行かせられます',
    politen: '連れて行かせられません' },
  { form: 'Conjectural',
    plainp: '連れて行くだろう',
    plainn: '連れて行かないだろう',
    politep: '連れて行くでしょう',
    politen: '連れて行かないでしょう' },
  { form: 'Alternative',
    plainp: '連れて行ったり',
    plainn: '連れて行かなかったり',
    politep: '連れて行きましたり',
    politen: '連れて行きませんでしたり' },
  { form: 'Imperative',
    plainp: '連れて行け',
    plainn: '連れて行くな',
    politep: '連れて行きなさい',
    politen: '連れて行きなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanku_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "mu" ending', function(done){
    var verbtest = data2[175942]['k_ele'][0]['keb'][0];
    var typetest = data2[175942]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanmu_test = [ { form: 'Present',
    plainp: '包む',
    plainn: '包まない',
    politep: '包みます',
    politen: '包みません' },
  { form: 'Past',
    plainp: '包んだ',
    plainn: '包まなかった',
    politep: '包みました',
    politen: '包みませんでした' },
  { form: 'Te',
    plainp: '包んで',
    plainn: '包まなくて',
    politep: '包みまして',
    politen: '包みませんで' },
  { form: 'Present Progressive',
    plainp: '包んでいる',
    plainn: '包んでいない',
    politep: '包んでいます',
    politen: '包んでいません' },
  { form: 'Volitional',
    plainp: '包もう',
    plainn: '包むまい',
    politep: '包みましょう',
    politen: '包みますまい' },
  { form: 'Desire (Present)',
    plainp: '包みたい',
    plainn: '包みたくない',
    politep: '包みたいです',
    politen: '包みたくないです' },
  { form: 'Desire (Past)',
    plainp: '包みたかった',
    plainn: '包みたくなかった',
    politep: '包みたかったです',
    politen: '包みたくなかったです' },
  { form: 'Conditional',
    plainp: '包んだら',
    plainn: '包まなかったら',
    politep: '包みましたら',
    politen: '包みませんでしたら' },
  { form: 'Provisional',
    plainp: '包めば',
    plainn: '包まなければ',
    politep: '包みますなら(ば)',
    politen: '包みませんなら(ば)' },
  { form: 'Potential',
    plainp: '包める',
    plainn: '包めない',
    politep: '包めます',
    politen: '包めません' },
  { form: 'Passive',
    plainp: '包まれる',
    plainn: '包まれない',
    politep: '包まれます',
    politen: '包まれません' },
  { form: 'Causative',
    plainp: '包ませる',
    plainn: '包ませない',
    politep: '包ませます',
    politen: '包ませません' },
  { form: 'Causative (Alt.)',
    plainp: '包ます',
    plainn: '包まさない',
    politep: '包まします',
    politen: '包ましません' },
  { form: 'Causative Passive',
    plainp: '包ませられる',
    plainn: '包ませられない',
    politep: '包ませられます',
    politen: '包ませられません' },
  { form: 'Conjectural',
    plainp: '包むだろう',
    plainn: '包まないだろう',
    politep: '包むでしょう',
    politen: '包まないでしょう' },
  { form: 'Alternative',
    plainp: '包んだり',
    plainn: '包まなかったり',
    politep: '包みましたり',
    politen: '包みませんでしたり' },
  { form: 'Imperative',
    plainp: '包め',
    plainn: '包むな',
    politep: '包みなさい',
    politen: '包みなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanmu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "nu" ending', function(done){
    var verbtest = data2[29125]['k_ele'][0]['keb'][0];
    var typetest = data2[29125]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godannu_test = [ { form: 'Present',
    plainp: '死ぬ',
    plainn: '死なない',
    politep: '死にます',
    politen: '死にません' },
  { form: 'Past',
    plainp: '死んだ',
    plainn: '死ななかった',
    politep: '死にました',
    politen: '死にませんでした' },
  { form: 'Te',
    plainp: '死んで',
    plainn: '死ななくて',
    politep: '死にまして',
    politen: '死にませんで' },
  { form: 'Present Progressive',
    plainp: '死んでいる',
    plainn: '死んでいない',
    politep: '死んでいます',
    politen: '死んでいません' },
  { form: 'Volitional',
    plainp: '死のう',
    plainn: '死ぬまい',
    politep: '死にましょう',
    politen: '死にますまい' },
  { form: 'Desire (Present)',
    plainp: '死にたい',
    plainn: '死にたくない',
    politep: '死にたいです',
    politen: '死にたくないです' },
  { form: 'Desire (Past)',
    plainp: '死にたかった',
    plainn: '死にたくなかった',
    politep: '死にたかったです',
    politen: '死にたくなかったです' },
  { form: 'Conditional',
    plainp: '死んだら',
    plainn: '死ななかったら',
    politep: '死にましたら',
    politen: '死にませんでしたら' },
  { form: 'Provisional',
    plainp: '死ねば',
    plainn: '死ななければ',
    politep: '死にますなら(ば)',
    politen: '死にませんなら(ば)' },
  { form: 'Potential',
    plainp: '死ねる',
    plainn: '死ねない',
    politep: '死ねます',
    politen: '死ねません' },
  { form: 'Passive',
    plainp: '死なれる',
    plainn: '死なれない',
    politep: '死なれます',
    politen: '死なれません' },
  { form: 'Causative',
    plainp: '死なせる',
    plainn: '死なせない',
    politep: '死なせます',
    politen: '死なせません' },
  { form: 'Causative (Alt.)',
    plainp: '死なす',
    plainn: '死なさない',
    politep: '死なします',
    politen: '死なしません' },
  { form: 'Causative Passive',
    plainp: '死なせられる',
    plainn: '死なせられない',
    politep: '死なせられます',
    politen: '死なせられません' },
  { form: 'Conjectural',
    plainp: '死ぬだろう',
    plainn: '死なないだろう',
    politep: '死ぬでしょう',
    politen: '死なないでしょう' },
  { form: 'Alternative',
    plainp: '死んだり',
    plainn: '死ななかったり',
    politep: '死にましたり',
    politen: '死にませんでしたり' },
  { form: 'Imperative',
    plainp: '死ね',
    plainn: '死ぬな',
    politep: '死になさい',
    politen: '死になさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godannu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "ru" ending', function(done){
    var verbtest = data2[137867]['k_ele'][0]['keb'][0];
    var typetest = data2[137867]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanru_test = [ { form: 'Present',
    plainp: '呼ばわる',
    plainn: '呼ばわらない',
    politep: '呼ばわります',
    politen: '呼ばわりません' },
  { form: 'Past',
    plainp: '呼ばわった',
    plainn: '呼ばわらなかった',
    politep: '呼ばわりました',
    politen: '呼ばわりませんでした' },
  { form: 'Te',
    plainp: '呼ばわって',
    plainn: '呼ばわらなくて',
    politep: '呼ばわりまして',
    politen: '呼ばわりませんで' },
  { form: 'Present Progressive',
    plainp: '呼ばわっている',
    plainn: '呼ばわっていない',
    politep: '呼ばわっています',
    politen: '呼ばわっていません' },
  { form: 'Volitional',
    plainp: '呼ばわろう',
    plainn: '呼ばわるまい',
    politep: '呼ばわりましょう',
    politen: '呼ばわりますまい' },
  { form: 'Desire (Present)',
    plainp: '呼ばわりたい',
    plainn: '呼ばわりたくない',
    politep: '呼ばわりたいです',
    politen: '呼ばわりたくないです' },
  { form: 'Desire (Past)',
    plainp: '呼ばわりたかった',
    plainn: '呼ばわりたくなかった',
    politep: '呼ばわりたかったです',
    politen: '呼ばわりたくなかったです' },
  { form: 'Conditional',
    plainp: '呼ばわったら',
    plainn: '呼ばわらなかったら',
    politep: '呼ばわりましたら',
    politen: '呼ばわりませんでしたら' },
  { form: 'Provisional',
    plainp: '呼ばわれば',
    plainn: '呼ばわらなければ',
    politep: '呼ばわりますなら(ば)',
    politen: '呼ばわりませんなら(ば)' },
  { form: 'Potential',
    plainp: '呼ばわれる',
    plainn: '呼ばわれない',
    politep: '呼ばわれます',
    politen: '呼ばわれません' },
  { form: 'Passive',
    plainp: '呼ばわられる',
    plainn: '呼ばわられない',
    politep: '呼ばわられます',
    politen: '呼ばわられません' },
  { form: 'Causative',
    plainp: '呼ばわらせる',
    plainn: '呼ばわらせない',
    politep: '呼ばわらせます',
    politen: '呼ばわらせません' },
  { form: 'Causative (Alt.)',
    plainp: '呼ばわらす',
    plainn: '呼ばわらさない',
    politep: '呼ばわらします',
    politen: '呼ばわらしません' },
  { form: 'Causative Passive',
    plainp: '呼ばわらせられる',
    plainn: '呼ばわらせられない',
    politep: '呼ばわらせられます',
    politen: '呼ばわらせられません' },
  { form: 'Conjectural',
    plainp: '呼ばわるだろう',
    plainn: '呼ばわらないだろう',
    politep: '呼ばわるでしょう',
    politen: '呼ばわらないでしょう' },
  { form: 'Alternative',
    plainp: '呼ばわったり',
    plainn: '呼ばわらなかったり',
    politep: '呼ばわりましたり',
    politen: '呼ばわりませんでしたり' },
  { form: 'Imperative',
    plainp: '呼ばわれ',
    plainn: '呼ばわるな',
    politep: '呼ばわりなさい',
    politen: '呼ばわりなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanru_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "su" ending', function(done){
    var verbtest = data2[176237]['k_ele'][0]['keb'][0];
    var typetest = data2[176237]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godansu_test = [ { form: 'Present',
    plainp: '笑かす',
    plainn: '笑かさない',
    politep: '笑かします',
    politen: '笑かしません' },
  { form: 'Past',
    plainp: '笑かした',
    plainn: '笑かさなかった',
    politep: '笑かしました',
    politen: '笑かしませんでした' },
  { form: 'Te',
    plainp: '笑かして',
    plainn: '笑かさなくて',
    politep: '笑かしまして',
    politen: '笑かしませんで' },
  { form: 'Present Progressive',
    plainp: '笑かしている',
    plainn: '笑かしていない',
    politep: '笑かしています',
    politen: '笑かしていません' },
  { form: 'Volitional',
    plainp: '笑かそう',
    plainn: '笑かすまい',
    politep: '笑かしましょう',
    politen: '笑かしますまい' },
  { form: 'Desire (Present)',
    plainp: '笑かしたい',
    plainn: '笑かしたくない',
    politep: '笑かしたいです',
    politen: '笑かしたくないです' },
  { form: 'Desire (Past)',
    plainp: '笑かしたかった',
    plainn: '笑かしたくなかった',
    politep: '笑かしたかったです',
    politen: '笑かしたくなかったです' },
  { form: 'Conditional',
    plainp: '笑かしたら',
    plainn: '笑かさなかったら',
    politep: '笑かしましたら',
    politen: '笑かしませんでしたら' },
  { form: 'Provisional',
    plainp: '笑かせば',
    plainn: '笑かさなければ',
    politep: '笑かしますなら(ば)',
    politen: '笑かしませんなら(ば)' },
  { form: 'Potential',
    plainp: '笑かせる',
    plainn: '笑かせない',
    politep: '笑かせます',
    politen: '笑かせません' },
  { form: 'Passive',
    plainp: '笑かされる',
    plainn: '笑かされない',
    politep: '笑かされます',
    politen: '笑かされません' },
  { form: 'Causative',
    plainp: '笑かさせる',
    plainn: '笑かさせない',
    politep: '笑かさせます',
    politen: '笑かさせません' },
  { form: 'Causative (Alt.)',
    plainp: '笑かさす',
    plainn: '笑かささない',
    politep: '笑かさします',
    politen: '笑かさしません' },
  { form: 'Causative Passive',
    plainp: '笑かさせられる',
    plainn: '笑かさせられない',
    politep: '笑かさせられます',
    politen: '笑かさせられません' },
  { form: 'Conjectural',
    plainp: '笑かすだろう',
    plainn: '笑かさないだろう',
    politep: '笑かすでしょう',
    politen: '笑かさないでしょう' },
  { form: 'Alternative',
    plainp: '笑かしたり',
    plainn: '笑かさなかったり',
    politep: '笑かしましたり',
    politen: '笑かしませんでしたり' },
  { form: 'Imperative',
    plainp: '笑かせ',
    plainn: '笑かすな',
    politep: '笑かしなさい',
    politen: '笑かしなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godansu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "tsu" ending', function(done){
    var verbtest = data2[56733]['k_ele'][0]['keb'][0];
    var typetest = data2[56733]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godantsu_test = [ { form: 'Present',
    plainp: '立つ',
    plainn: '立たない',
    politep: '立ちます',
    politen: '立ちません' },
  { form: 'Past',
    plainp: '立った',
    plainn: '立たなかった',
    politep: '立ちました',
    politen: '立ちませんでした' },
  { form: 'Te',
    plainp: '立って',
    plainn: '立たなくて',
    politep: '立ちまして',
    politen: '立ちませんで' },
  { form: 'Present Progressive',
    plainp: '立っている',
    plainn: '立っていない',
    politep: '立っています',
    politen: '立っていません' },
  { form: 'Volitional',
    plainp: '立とう',
    plainn: '立つまい',
    politep: '立ちましょう',
    politen: '立ちますまい' },
  { form: 'Desire (Present)',
    plainp: '立ちたい',
    plainn: '立ちたくない',
    politep: '立ちたいです',
    politen: '立ちたくないです' },
  { form: 'Desire (Past)',
    plainp: '立ちたかった',
    plainn: '立ちたくなかった',
    politep: '立ちたかったです',
    politen: '立ちたくなかったです' },
  { form: 'Conditional',
    plainp: '立ったら',
    plainn: '立たなかったら',
    politep: '立ちましたら',
    politen: '立ちませんでしたら' },
  { form: 'Provisional',
    plainp: '立てば',
    plainn: '立たなければ',
    politep: '立ちますなら(ば)',
    politen: '立ちませんなら(ば)' },
  { form: 'Potential',
    plainp: '立てる',
    plainn: '立てない',
    politep: '立てます',
    politen: '立てません' },
  { form: 'Passive',
    plainp: '立たれる',
    plainn: '立たれない',
    politep: '立たれます',
    politen: '立たれません' },
  { form: 'Causative',
    plainp: '立たせる',
    plainn: '立たせない',
    politep: '立たせます',
    politen: '立たせません' },
  { form: 'Causative (Alt.)',
    plainp: '立たす',
    plainn: '立たさない',
    politep: '立たします',
    politen: '立たしません' },
  { form: 'Causative Passive',
    plainp: '立たせられる',
    plainn: '立たせられない',
    politep: '立たせられます',
    politen: '立たせられません' },
  { form: 'Conjectural',
    plainp: '立つだろう',
    plainn: '立たないだろう',
    politep: '立つでしょう',
    politen: '立たないでしょう' },
  { form: 'Alternative',
    plainp: '立ったり',
    plainn: '立たなかったり',
    politep: '立ちましたり',
    politen: '立ちませんでしたり' },
  { form: 'Imperative',
    plainp: '立て',
    plainn: '立つな',
    politep: '立ちなさい',
    politen: '立ちなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godantsu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "u" ending', function(done){
    var verbtest = data2[177280]['k_ele'][0]['keb'][0];
    var typetest = data2[177280]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanu_test = [ { form: 'Present',
    plainp: '購う',
    plainn: '購わない',
    politep: '購います',
    politen: '購いません' },
  { form: 'Past',
    plainp: '購った',
    plainn: '購わなかった',
    politep: '購いました',
    politen: '購いませんでした' },
  { form: 'Te',
    plainp: '購って',
    plainn: '購わなくて',
    politep: '購いまして',
    politen: '購いませんで' },
  { form: 'Present Progressive',
    plainp: '購っている',
    plainn: '購っていない',
    politep: '購っています',
    politen: '購っていません' },
  { form: 'Volitional',
    plainp: '購おう',
    plainn: '購うまい',
    politep: '購いましょう',
    politen: '購いますまい' },
  { form: 'Desire (Present)',
    plainp: '購いたい',
    plainn: '購いたくない',
    politep: '購いたいです',
    politen: '購いたくないです' },
  { form: 'Desire (Past)',
    plainp: '購いたかった',
    plainn: '購いたくなかった',
    politep: '購いたかったです',
    politen: '購いたくなかったです' },
  { form: 'Conditional',
    plainp: '購ったら',
    plainn: '購わなかったら',
    politep: '購いましたら',
    politen: '購いませんでしたら' },
  { form: 'Provisional',
    plainp: '購えば',
    plainn: '購わなければ',
    politep: '購いますなら(ば)',
    politen: '購いませんなら(ば)' },
  { form: 'Potential',
    plainp: '購える',
    plainn: '購えない',
    politep: '購えます',
    politen: '購えません' },
  { form: 'Passive',
    plainp: '購われる',
    plainn: '購われない',
    politep: '購われます',
    politen: '購われません' },
  { form: 'Causative',
    plainp: '購わせる',
    plainn: '購わせない',
    politep: '購わせます',
    politen: '購わせません' },
  { form: 'Causative (Alt.)',
    plainp: '購わす',
    plainn: '購わさない',
    politep: '購わします',
    politen: '購わしません' },
  { form: 'Causative Passive',
    plainp: '購わせられる',
    plainn: '購わせられない',
    politep: '購わせられます',
    politen: '購わせられません' },
  { form: 'Conjectural',
    plainp: '購うだろう',
    plainn: '購わないだろう',
    politep: '購うでしょう',
    politen: '購わないでしょう' },
  { form: 'Alternative',
    plainp: '購ったり',
    plainn: '購わなかったり',
    politep: '購いましたり',
    politen: '購いませんでしたり' },
  { form: 'Imperative',
    plainp: '購え',
    plainn: '購うな',
    politep: '購いなさい',
    politen: '購いなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Godan Verb - "u" (special) ending', function(done){
    var verbtest = data2[53124]['k_ele'][0]['keb'][0];
    var typetest = data2[53124]['sense'][0]['pos'][0];
    var godan = conjugateVerb.conjugate(verbtest, typetest);

    var godanu_test = [ { form: 'Present',
    plainp: '恋う',
    plainn: '恋わない',
    politep: '恋います',
    politen: '恋いません' },
  { form: 'Past',
    plainp: '恋うた',
    plainn: '恋わなかった',
    politep: '恋いました',
    politen: '恋いませんでした' },
  { form: 'Te',
    plainp: '恋うて',
    plainn: '恋わなくて',
    politep: '恋いまして',
    politen: '恋いませんで' },
  { form: 'Present Progressive',
    plainp: '恋うている',
    plainn: '恋うていない',
    politep: '恋うています',
    politen: '恋うていません' },
  { form: 'Volitional',
    plainp: '恋おう',
    plainn: '恋うまい',
    politep: '恋いましょう',
    politen: '恋いますまい' },
  { form: 'Desire (Present)',
    plainp: '恋いたい',
    plainn: '恋いたくない',
    politep: '恋いたいです',
    politen: '恋いたくないです' },
  { form: 'Desire (Past)',
    plainp: '恋いたかった',
    plainn: '恋いたくなかった',
    politep: '恋いたかったです',
    politen: '恋いたくなかったです' },
  { form: 'Conditional',
    plainp: '恋うたら',
    plainn: '恋わなかったら',
    politep: '恋いましたら',
    politen: '恋いませんでしたら' },
  { form: 'Provisional',
    plainp: '恋えば',
    plainn: '恋わなければ',
    politep: '恋いますなら(ば)',
    politen: '恋いませんなら(ば)' },
  { form: 'Potential',
    plainp: '恋える',
    plainn: '恋えない',
    politep: '恋えます',
    politen: '恋えません' },
  { form: 'Passive',
    plainp: '恋われる',
    plainn: '恋われない',
    politep: '恋われます',
    politen: '恋われません' },
  { form: 'Causative',
    plainp: '恋わせる',
    plainn: '恋わせない',
    politep: '恋わせます',
    politen: '恋わせません' },
  { form: 'Causative (Alt.)',
    plainp: '恋わす',
    plainn: '恋わさない',
    politep: '恋わします',
    politen: '恋わしません' },
  { form: 'Causative Passive',
    plainp: '恋わせられる',
    plainn: '恋わせられない',
    politep: '恋わせられます',
    politen: '恋わせられません' },
  { form: 'Conjectural',
    plainp: '恋うだろう',
    plainn: '恋わないだろう',
    politep: '恋うでしょう',
    politen: '恋わないでしょう' },
  { form: 'Alternative',
    plainp: '恋うたり',
    plainn: '恋わなかったり',
    politep: '恋いましたり',
    politen: '恋いませんでしたり' },
  { form: 'Imperative',
    plainp: '恋え',
    plainn: '恋うな',
    politep: '恋いなさい',
    politen: '恋いなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godanu_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();
  });

  it('Conjugate Godan Verb - "aru" Class', function(done){
    var verbtest = data2[16908]['k_ele'][0]['keb'][0];
    var typetest = data2[16908]['sense'][0]['pos'][0];
    var godan= conjugateVerb.conjugate(verbtest, typetest);

    var godan_test = [ { form: 'Present',
    plainp: '下さる',
    plainn: '下さらない',
    politep: '下さいます',
    politen: '下さいません' },
  { form: 'Past',
    plainp: '下さった',
    plainn: '下さらなかった',
    politep: '下さいました',
    politen: '下さいませんでした' },
  { form: 'Te',
    plainp: '下さって',
    plainn: '下さらなくて',
    politep: '下さいまして',
    politen: '下さいませんで' },
  { form: 'Present Progressive',
    plainp: '下さっている',
    plainn: '下さっていない',
    politep: '下さっています',
    politen: '下さっていません' },
  { form: 'Volitional',
    plainp: '下さろう',
    plainn: '下さるまい',
    politep: '下さいましょう',
    politen: '下さいますまい' },
  { form: 'Desire (Present)',
    plainp: '下さいたい',
    plainn: '下さいたくない',
    politep: '下さいたいです',
    politen: '下さいたくないです' },
  { form: 'Desire (Past)',
    plainp: '下さいたかった',
    plainn: '下さいたくなかった',
    politep: '下さいたかったです',
    politen: '下さいたくなかったです' },
  { form: 'Conditional',
    plainp: '下さったら',
    plainn: '下さらなかったら',
    politep: '下さいましたら',
    politen: '下さいませんでしたら' },
  { form: 'Provisional',
    plainp: '下されば',
    plainn: '下さらなければ',
    politep: '下さいますなら(ば)',
    politen: '下さいませんなら(ば)' },
  { form: 'Potential',
    plainp: '下される',
    plainn: '下されない',
    politep: '下されます',
    politen: '下されません' },
  { form: 'Passive',
    plainp: '下さられる',
    plainn: '下さられない',
    politep: '下さられます',
    politen: '下さられません' },
  { form: 'Causative',
    plainp: '下さらせる',
    plainn: '下さらせない',
    politep: '下さらせます',
    politen: '下さらせません' },
  { form: 'Causative (Alt.)',
    plainp: '下さらす',
    plainn: '下さらさない',
    politep: '下さらします',
    politen: '下さらしません' },
  { form: 'Causative Passive',
    plainp: '下さらせられる',
    plainn: '下さらせられない',
    politep: '下さらせられます',
    politen: '下さらせられません' },
  { form: 'Conjectural',
    plainp: '下さるだろう',
    plainn: '下さらないだろう',
    politep: '下さるでしょう',
    politen: '下さらないでしょう' },
  { form: 'Alternative',
    plainp: '下さったり',
    plainn: '下さらなかったり',
    politep: '下さいましたり',
    politen: '下さいませんでしたり' },
  { form: 'Imperative',
    plainp: '下さい',
    plainn: '下さるな',
    politep: '下さいなさい',
    politen: '下さいなさるな' } ];
    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godan_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

    it('Conjugate Godan Verb - "aru" ending irregular', function(done){
    var verbtest = data2[101737]['r_ele'][0]['reb'][0];
    var typetest = data2[101737]['sense'][0]['pos'][0];
    var godan= conjugateVerb.conjugate(verbtest, typetest);

    var godan_test = [ { form: 'Present',
    plainp: 'でもある',
    plainn: 'でもない',
    politep: 'でもあります',
    politen: 'でもありません' },
  { form: 'Past',
    plainp: 'でもあった',
    plainn: 'でもなかった',
    politep: 'でもありました',
    politen: 'でもありませんでした' },
  { form: 'Te',
    plainp: 'でもあって',
    plainn: 'でもなくて',
    politep: 'でもありまして',
    politen: 'でもありませんで' },
  { form: 'Present Progressive',
    plainp: 'でもあっている',
    plainn: 'でもあっていない',
    politep: 'でもあっています',
    politen: 'でもあっていません' },
  { form: 'Volitional',
    plainp: 'でもあろう',
    plainn: 'でもあるまい',
    politep: 'でもありましょう',
    politen: 'でもありますまい' },
  { form: 'Desire (Present)',
    plainp: 'でもありたい',
    plainn: 'でもありたくない',
    politep: 'でもありたいです',
    politen: 'でもありたくないです' },
  { form: 'Desire (Past)',
    plainp: 'でもありたかった',
    plainn: 'でもありたくなかった',
    politep: 'でもありたかったです',
    politen: 'でもありたくなかったです' },
  { form: 'Conditional',
    plainp: 'でもあったら',
    plainn: 'でもなかったら',
    politep: 'でもありましたら',
    politen: 'でもありませんでしたら' },
  { form: 'Provisional',
    plainp: 'でもあれば',
    plainn: 'でもなければ',
    politep: 'でもありますなら(ば)',
    politen: 'でもありませんなら(ば)' },
  { form: 'Potential',
    plainp: 'でもあれる',
    plainn: 'でもあれない',
    politep: 'でもあれます',
    politen: 'でもあれません' },
  { form: 'Passive',
    plainp: 'でもあられる',
    plainn: 'でもあられない',
    politep: 'でもあられます',
    politen: 'でもあられません' },
  { form: 'Causative',
    plainp: 'でもあらせる',
    plainn: 'でもあらせない',
    politep: 'でもあらせます',
    politen: 'でもあらせません' },
  { form: 'Causative (Alt.)',
    plainp: 'でもあらす',
    plainn: 'でもあらさない',
    politep: 'でもあらします',
    politen: 'でもあらしません' },
  { form: 'Causative Passive',
    plainp: 'でもあらせられる',
    plainn: 'でもあらせられない',
    politep: 'でもあらせられます',
    politen: 'でもあらせられません' },
  { form: 'Conjectural',
    plainp: 'でもあるだろう',
    plainn: 'でもないだろう',
    politep: 'でもあるでしょう',
    politen: 'でもないでしょう' },
  { form: 'Alternative',
    plainp: 'でもあったり',
    plainn: 'でもなかったり',
    politep: 'でもありましたり',
    politen: 'でもありませんでしたり' },
  { form: 'Imperative',
    plainp: 'でもあれ',
    plainn: 'でもあるな',
    politep: 'でもありなさい',
    politen: 'でもありなさるな' } ];

    for (var i = 0; i < godan.length; i ++) {
      assert.deepStrictEqual(godan[i], godan_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Kuru Verb', function(done){
    var verbtest = data2[52067]['k_ele'][0]['keb'][0];
    var typetest = data2[52067]['sense'][0]['pos'][0];
    var kuru = conjugateVerb.conjugate(verbtest, typetest);

    var kuru_test = [ { form: 'Present',
    plainp: '来る',
    plainn: '来ない',
    politep: '来ます',
    politen: '来ません' },
  { form: 'Past',
    plainp: '来た',
    plainn: '来なかった',
    politep: '来ました',
    politen: '来ませんでした' },
  { form: 'Te',
    plainp: '来て',
    plainn: '来なくて',
    politep: '来まして',
    politen: '来ませんで' },
  { form: 'Present Progressive',
    plainp: '来ている',
    plainn: '来ていない',
    politep: '来ています',
    politen: '来ていません' },
  { form: 'Volitional',
    plainp: '来よう',
    plainn: '来るまい',
    politep: '来ましょう',
    politen: '来ますまい' },
  { form: 'Desire (Present)',
    plainp: '来たい',
    plainn: '来たくない',
    politep: '来たいです',
    politen: '来たくないです' },
  { form: 'Desire (Past)',
    plainp: '来たかった',
    plainn: '来たくなかった',
    politep: '来たかったです',
    politen: '来たくなかったです' },
  { form: 'Conditional',
    plainp: '来たら',
    plainn: '来なかったら',
    politep: '来ましたら',
    politen: '来ませんでしたら' },
  { form: 'Provisional',
    plainp: '来れば',
    plainn: '来なければ',
    politep: '来ますなら(ば)',
    politen: '来ませんなら(ば)' },
  { form: 'Potential',
    plainp: '来られる',
    plainn: '来られない',
    politep: '来られます',
    politen: '来られません' },
  { form: 'Passive',
    plainp: '来られる',
    plainn: '来られない',
    politep: '来られます',
    politen: '来られません' },
  { form: 'Causative',
    plainp: '来させる',
    plainn: '来させない',
    politep: '来させます',
    politen: '来させません' },
  { form: 'Causative (Alt.)',
    plainp: '来さす',
    plainn: '来ささない',
    politep: '来さします',
    politen: '来さしません' },
  { form: 'Causative Passive',
    plainp: '来させられる',
    plainn: '来させられない',
    politep: '来させられます',
    politen: '来させられません' },
  { form: 'Conjectural',
    plainp: '来るだろう',
    plainn: '来ないだろう',
    politep: '来るでしょう',
    politen: '来ないでしょう' },
  { form: 'Alternative',
    plainp: '来たり',
    plainn: '来なかったり',
    politep: '来ましたり',
    politen: '来ませんでしたり' },
  { form: 'Imperative',
    plainp: '来い',
    plainn: '来るな',
    politep: '来なさい',
    politen: '来なさるな' } ];

    for (var i = 0; i < kuru.length; i ++) {
      assert.deepStrictEqual(kuru[i], kuru_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Suru (Aux) Verb', function(done){
    var verbtest = data2[53234]['k_ele'][0]['keb'][0];
    var typetest = data2[53234]['sense'][0]['pos'][0];
    var suru = conjugateVerb.conjugate(verbtest, typetest);

    var suru_test = [ { form: 'Present',
    plainp: '連絡する',
    plainn: '連絡しない',
    politep: '連絡します',
    politen: '連絡しません' },
  { form: 'Past',
    plainp: '連絡した',
    plainn: '連絡しなかった',
    politep: '連絡しました',
    politen: '連絡しませんでした' },
  { form: 'Te',
    plainp: '連絡して',
    plainn: '連絡しなくて',
    politep: '連絡しまして',
    politen: '連絡しませんで' },
  { form: 'Present Progressive',
    plainp: '連絡している',
    plainn: '連絡していない',
    politep: '連絡しています',
    politen: '連絡していません' },
  { form: 'Volitional',
    plainp: '連絡しよう',
    plainn: '連絡するまい',
    politep: '連絡しましょう',
    politen: '連絡しますまい' },
  { form: 'Desire (Present)',
    plainp: '連絡したい',
    plainn: '連絡したくない',
    politep: '連絡したいです',
    politen: '連絡したくないです' },
  { form: 'Desire (Past)',
    plainp: '連絡したかった',
    plainn: '連絡したくなかった',
    politep: '連絡したかったです',
    politen: '連絡したくなかったです' },
  { form: 'Conditional',
    plainp: '連絡したら',
    plainn: '連絡しなかったら',
    politep: '連絡しましたら',
    politen: '連絡しませんでしたら' },
  { form: 'Provisional',
    plainp: '連絡すれば',
    plainn: '連絡しなければ',
    politep: '連絡しますなら(ば)',
    politen: '連絡しませんなら(ば)' },
  { form: 'Potential',
    plainp: '連絡できる',
    plainn: '連絡できない',
    politep: '連絡できます',
    politen: '連絡できません' },
  { form: 'Passive',
    plainp: '連絡される',
    plainn: '連絡されない',
    politep: '連絡されます',
    politen: '連絡されません' },
  { form: 'Causative',
    plainp: '連絡させる',
    plainn: '連絡させない',
    politep: '連絡させます',
    politen: '連絡させません' },
  { form: 'Causative (Alt.)',
    plainp: '連絡さす',
    plainn: '連絡ささない',
    politep: '連絡さします',
    politen: '連絡さしません' },
  { form: 'Causative Passive',
    plainp: '連絡させられる',
    plainn: '連絡させられない',
    politep: '連絡させられます',
    politen: '連絡させられません' },
  { form: 'Conjectural',
    plainp: '連絡するだろう',
    plainn: '連絡しないだろう',
    politep: '連絡するでしょう',
    politen: '連絡しないでしょう' },
  { form: 'Alternative',
    plainp: '連絡したり',
    plainn: '連絡しなかったり',
    politep: '連絡しましたり',
    politen: '連絡しませんでしたり' },
  { form: 'Imperative',
    plainp: '連絡しろ',
    plainn: '連絡するな',
    politep: '連絡しなさい',
    politen: '連絡しなさるな' } ];
    for (var i = 0; i < suru.length; i ++) {
      assert.deepStrictEqual(suru[i], suru_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Suru (Irregular) Verb', function(done){
    var verbtest = data2[14312]['k_ele'][0]['keb'][0];
    var typetest = data2[14312]['sense'][0]['pos'][0];
    var suru = conjugateVerb.conjugate(verbtest, typetest);

    var suru_test = [ { form: 'Present',
    plainp: 'する',
    plainn: 'しない',
    politep: 'します',
    politen: 'しません' },
  { form: 'Past',
    plainp: 'した',
    plainn: 'しなかった',
    politep: 'しました',
    politen: 'しませんでした' },
  { form: 'Te',
    plainp: 'して',
    plainn: 'しなくて',
    politep: 'しまして',
    politen: 'しませんで' },
  { form: 'Present Progressive',
    plainp: 'している',
    plainn: 'していない',
    politep: 'しています',
    politen: 'していません' },
  { form: 'Volitional',
    plainp: 'しよう',
    plainn: 'するまい',
    politep: 'しましょう',
    politen: 'しますまい' },
  { form: 'Desire (Present)',
    plainp: 'したい',
    plainn: 'したくない',
    politep: 'したいです',
    politen: 'したくないです' },
  { form: 'Desire (Past)',
    plainp: 'したかった',
    plainn: 'したくなかった',
    politep: 'したかったです',
    politen: 'したくなかったです' },
  { form: 'Conditional',
    plainp: 'したら',
    plainn: 'しなかったら',
    politep: 'しましたら',
    politen: 'しませんでしたら' },
  { form: 'Provisional',
    plainp: 'すれば',
    plainn: 'しなければ',
    politep: 'しますなら(ば)',
    politen: 'しませんなら(ば)' },
  { form: 'Potential',
    plainp: 'できる',
    plainn: 'できない',
    politep: 'できます',
    politen: 'できません' },
  { form: 'Passive',
    plainp: 'される',
    plainn: 'されない',
    politep: 'されます',
    politen: 'されません' },
  { form: 'Causative',
    plainp: 'させる',
    plainn: 'させない',
    politep: 'させます',
    politen: 'させません' },
  { form: 'Causative (Alt.)',
    plainp: 'さす',
    plainn: 'ささない',
    politep: 'さします',
    politen: 'さしません' },
  { form: 'Causative Passive',
    plainp: 'させられる',
    plainn: 'させられない',
    politep: 'させられます',
    politen: 'させられません' },
  { form: 'Conjectural',
    plainp: 'するだろう',
    plainn: 'しないだろう',
    politep: 'するでしょう',
    politen: 'しないでしょう' },
  { form: 'Alternative',
    plainp: 'したり',
    plainn: 'しなかったり',
    politep: 'しましたり',
    politen: 'しませんでしたり' },
  { form: 'Imperative',
    plainp: 'しろ',
    plainn: 'するな',
    politep: 'しなさい',
    politen: 'しなさるな' } ];
    for (var i = 0; i < suru.length; i ++) {
      assert.deepStrictEqual(suru[i], suru_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });

  it('Conjugate Suru (Special) Verb', function(done){
    var verbtest = data2[169056]['k_ele'][0]['keb'][0];
    var typetest = data2[169056]['sense'][0]['pos'][0];
    var suru = conjugateVerb.conjugate(verbtest, typetest);

    var suru_test = [ { form: 'Present',
    plainp: '管する',
    plainn: '管さない',
    politep: '管します',
    politen: '管しません' },
  { form: 'Past',
    plainp: '管した',
    plainn: '管さなかった',
    politep: '管しました',
    politen: '管しませんでした' },
  { form: 'Te',
    plainp: '管して',
    plainn: '管さなくて',
    politep: '管しまして',
    politen: '管しませんで' },
  { form: 'Present Progressive',
    plainp: '管している',
    plainn: '管していない',
    politep: '管しています',
    politen: '管していません' },
  { form: 'Volitional',
    plainp: '管しよう',
    plainn: '管するまい',
    politep: '管しましょう',
    politen: '管しますまい' },
  { form: 'Desire (Present)',
    plainp: '管したい',
    plainn: '管したくない',
    politep: '管したいです',
    politen: '管したくないです' },
  { form: 'Desire (Past)',
    plainp: '管したかった',
    plainn: '管したくなかった',
    politep: '管したかったです',
    politen: '管したくなかったです' },
  { form: 'Conditional',
    plainp: '管したら',
    plainn: '管さなかったら',
    politep: '管しましたら',
    politen: '管しませんでしたら' },
  { form: 'Provisional',
    plainp: '管すれば',
    plainn: '管さなければ',
    politep: '管しますなら(ば)',
    politen: '管しませんなら(ば)' },
  { form: 'Potential',
    plainp: '管しえる',
    plainn: '管しえない',
    politep: '管しえます',
    politen: '管しえません' },
  { form: 'Passive',
    plainp: '管される',
    plainn: '管されない',
    politep: '管されます',
    politen: '管されません' },
  { form: 'Causative',
    plainp: '管させる',
    plainn: '管させない',
    politep: '管させます',
    politen: '管させません' },
  { form: 'Causative (Alt.)',
    plainp: '管さす',
    plainn: '管ささない',
    politep: '管さします',
    politen: '管さしません' },
  { form: 'Causative Passive',
    plainp: '管させられる',
    plainn: '管させられない',
    politep: '管させられます',
    politen: '管させられません' },
  { form: 'Conjectural',
    plainp: '管するだろう',
    plainn: '管さないだろう',
    politep: '管するでしょう',
    politen: '管さないでしょう' },
  { form: 'Alternative',
    plainp: '管したり',
    plainn: '管さなかったり',
    politep: '管しましたり',
    politen: '管しませんでしたり' },
  { form: 'Imperative',
    plainp: '管しろ',
    plainn: '管するな',
    politep: '管しなさい',
    politen: '管しなさるな' } ];
    for (var i = 0; i < suru.length; i ++) {
      assert.deepStrictEqual(suru[i], suru_test[i], 'ConjugationError: Form(s) do not match');
    }

    done();

  });




});
