module.exports = verbMap = {
  '&vt;'   : 'Transitive Verb',
  '&vi;'   : 'Intransitive Verb',
  '&vr;'   : 'Irregular る verb, plain form ends with -り',
  '&vk;'   : 'Special Class くる Verb',
  '&vn;'   : 'Irregular ぬ verb',
  '&vs;'   : 'Noun / Participle that takes aux. verb する',
  '&vs-i;' : 'Irregular する verb',
  '&vs-s;' : 'Special class, する verb',
  '&vs-c;' : 'す verb - precursor to the modern する',
  '&vn;'   : 'Irregular ぬ verb',
  '&vi;'   : 'Intransitive Verb',
  '&v1;'   : 'Ichidan Verb',
  '&v1-s;' : 'Ichidan Verb - くれる special class',
  '&v4k;'  : 'Yodan verb with く ending (archaic)',
  '&v4r;'  : 'Yodan verb with る ending (archaic)',
  '&v4t;'  : 'Yodan verb with つ ending (archaic)',
  '&v5aru;': 'Godan verb - ある special class	',
  '&v5b;'  : 'Godan Verb with ぶ ending',
  '&v5g;'  : 'Godan Verb with ぐ ending',
  '&v5k;'  : 'Godan Verb with く ending',
  '&v5k-s;': 'Godan verb - 行く special class',
  '&v5m;'  : 'Godan Verb with む ending',
  '&v5n;'  : 'Godan Verb with ぬ ending',
  '&v5r;'  : 'Godan Verb with る ending',
  '&v5r-i;': 'Godan Verb with る irregular ending',
  '&v5s;'  : 'Godan Verb with す ending',
  '&v5t;'  : 'Godan Verb with つ ending',
  '&v5u;'  : 'Godan Verb with う ending',
  '&v5u-s;': 'Godan Verb with う ending special class',
  '&v5uru;': 'Godan verb - うる old class verb (old form of えるお)',
  '&aux-v;': 'Auxiliary Verb',
  '&adv-to;':'Adverb taking the "と" particle',
  '&adv;'  : 'Adverb',
  '&n;'    : 'Noun',
  '&suf;'  : 'Suffix',
  '&exp;'  : 'Expression',
  '&adj-f;': 'Noun / Verb acting prenominally',
  '&adj-na;': 'Adjectival nouns or quasi-adjectives',
  '&adj-pn;': 'Pre-noun adjectival',
  '&adj-no;': 'Nouns which may take the genitive case particle "の"',
}

module.exports = miscMap = {
  '&uk;'    : 'Usually written using kana alone',
  '&hon;'   : 'Honorific (尊敬語) language',
  '&hum;'   : 'Humble (謙譲語) language',
  '&pol;'   : 'Polite (丁寧語) language',
  '&sumo;'  : 'Sumo term',
  '&sens;'  : 'Sensitive',
  '&shogi;' : 'Shogi term',
  '&mahj;'  : 'Mahjong term',
  '&baseb;' : 'Baseball term',
  '&on-mim;': 'Onomatopoeic or mimetic',
  '&col;'   : 'Colloquialism',
  '&derog;' : 'Derogatory',
  '&abbr;'  : 'Abbreviation',
  '&sports;' : 'Sports term',
  '&comp;'  : 'Computing term',
  '&arch;'  : 'Archaism',
  '&ksb;'   : 'Kansai-ben',
  '&ktb;'   : 'Kantou-ben',
  '&kyb;'   : 'Kyoto-ben',
  '&kyu;'   : 'Kyuushuu-ben',
  '&math;'  : 'Math term',
  '&ling;'  : 'Linguistics term',
  '&obsc;'  : 'Obscure',
  '&obs;'   : 'Obsolete',
  '&vulg;'  : 'Vulgar expression',
  '&sl;'    : 'Slang',
  '&MA;'    : 'Martial Arts term',
  '&sumo;'  : 'Sumo term',
  '&food;'  : 'Food term',
  '&law;'   : 'Law term',
  '&id;'    : 'Idiomatic expression',
  '&Buddh;' : 'Buddhist term',
  '&male;'  : 'Male term, language, or name',
  '&m-sl;'  : 'Manga slang',
  '&poet;'  : 'Poetical term',
  '&joc;'   : 'Jocular, humorous term',
  '&chn;'   : "Children's Language",
  '&fam;'   : 'Familiar language',
  '&rare;'  : 'Rare',
  '&finc;'  : 'Finance term',

};