export const CHANGE_FORM_VALUE = 'CHANGE_FORM_VALUE';
export const CHANGE_QUERY_VALUE = 'CHANGE_QUERY_VALUE';
export const CHANGE_ACTIVE_PAGE = 'CHANGE_ACTIVE_PAGE';
export const ADD_PAGE_ITEM = 'ADD_PAGE_ITEM';
export const RESET_PAGES = 'RESET_PAGES';
export const SET_RESULTS_LENGTH = 'SET_RESULTS_LENGTH';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';